baseURL = 'https://musicmichaelc.com'
languageCode = 'en-us'
theme = 'coming-soon'

[params]
  title = "Michael Christensen's music site"
  description = "Stay tuned for more..."
  favicon = ""
  message = "Coming soon..." 
  release = "Feb 13, 2024 12:00" 
  background = ""